bitbucket_url: "changeme"
bitbucket_user: "changeme"
bitbucket_user_email: "changeme"
bitbucket_timeout: 1
bitbucket_password: "changeme"
github_user: "changeme"
github_password: "changeme"
github_token: "changeme"
port: "8080"
bitbucket_template_repositories:
  - name: "GoATT Microservice"
    project_key: "COM"
    repository_slug: "go-goatt-template"
    functional_domain: "Common"
    project_name: "go-goatt-template"
github_template_repositories:
  - name: "changeme"
    domain: "changeme"
    repo_name: "changeme"